### ISSUE TITLE
Thank you for releasing the code

### ISSUE THREAD

**Issue by DabiaoMa** [facebookresearch/loop#1]
I have tried to rebuild this model based on the details mentioned in the paper, but the result is bad. I used adam optimizer with 0.0002 lr and 0.5/0.9 momentum as well as gradient clip 1, but the gradient still explodes at the first few epochs. Now I can check what is wrong with my implementation.

**Comment by adampolyak** [comment]
Thank you, I hope the repo will help you.

**Comment by jayavanth** [comment]
@DabiaoMa were you able to fix the explosion?
