### ISSUE TITLE
slow down the voice

### ISSUE THREAD

**Issue by dengbingfeng** [facebookresearch/loop#12]
I find it speak too fast, how can I slow down the voice?

**Comment by karandwivedi42** [comment]
Did you figure out any solution?

**Comment by dengbingfeng** [comment]
@karandwivedi42, I think it all depends on the training data

**Comment by adampolyak** [comment]
Yea, it depends on the training data.

It is also possible to change the value of **attention-alignment**  during generation from 0.05 to 0.04 or 0.03. Simply add the following to generate.py:
`train_args.attention_alignment = 0.04`
