### ISSUE TITLE
shape mismatch of "audio_features"  between downloaded and generated npz files

### ISSUE THREAD

**Issue by abhinonymous** [facebookresearch/loop#16]
There is a shape mismatch in the audio_features array of npz files between data uploaded by you and npz generated by using your extract_features script by Kyle.

For eg.
in p299_405.npz,
shape of audio_features is (393,60) for uploaded npz file
shape is (829,60)  for npz created by the extract_feats script.

This issue could possibly stem from silences not being removed by the extract_feats script, while it has been removed from the uploaded data.

Can you please recommend a solution for this?

**Comment by hepower** [comment]
@abhinonymous , have you found any clues on this feature dismatch issue?

**Comment by adampolyak** [comment]
Indeed, trailing silence should be removed.
