### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by jayavanth** [facebookresearch/loop#17]
I trained loop with a subset of vctk data (American speakers). I found that the audio from those speakers when I run generate.py using my trained model are pretty bad. I just hear only a couple of words in a sentence and the rest is silence or noise.

My guess is that something went wrong during feature extraction. When I compare same feature extracted files i.e. p294_001.npz from the given s3 bucket and the one I feature extracted by running extract_feats.py, I see that `vuv_idx` from s3 has larger numbers (range: -5 to 5) compared to mine (range:  -10e-02 to 5 )

I also noticed that `text_features` and `audio_features` are of different shape:
(226, 420) - s3
(540, 420) - me

Other features like `durations` and `code2phone` also look different.

May I know what changes I've to make to the `extract_feats.py` to get similar features as the one in s3?

**Comment by hepower** [comment]
I also find the issue that the npz file size generated using extract_feats.py in local is different with the ones download from the site with download_data.sh , what is the problem?

**Comment by hepower** [comment]
@jayavanth have you fix the shape mismatch issue?

**Comment by adampolyak** [comment]
Mismatch in length is due to silence removal - preceding silence was removed from the uploaded data.
See #25.
