### ISSUE TITLE
Getting errors in generate.py

### ISSUE THREAD

**Issue by amitabhpatil** [facebookresearch/loop#18]
`python generate.py  --npz data/vctk/numpy_features_valid/p318_212.npz --spkr 13 --checkpoint models/vctk/bestmodel.pth
Traceback (most recent call last):
  File "generate.py", line 153, in <module>
    main()
  File "generate.py", line 142, in main
    norm_path)
  File "/mnt/sdb1/Learning/pytorch/loop/utils.py", line 257, in generate_merlin_wav
    weight=os.path.join(gen_dir, 'weight')), shell=True)
  File "/mnt/sdb1/Learning/pytorch/loop/utils.py", line 121, in pe
    for line in execute(cmd, shell=shell):
  File "/mnt/sdb1/Learning/pytorch/loop/utils.py", line 114, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'echo 1 1 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4  | /mnt/sdb1/Learning/pytorch/loop/tools/SPTK-3.9/x2x +af > /mnt/sdb1/Learning/pytorch/loop/models/vctk/results/weight' returned non-zero exit status 127
`

**Comment by gowthambruse** [comment]
**Reinstall the SPTK tools:**
sudo chmod +x download_tools.sh
./download_tools.sh
mv tools/ ../
python generate.py  --npz data/vctk/numpy_features_valid/p318_212.npz --spkr 13 --checkpoint models/vctk/bestmodel.pth
`python generate.py  --npz data/vctk/numpy_features_valid/p318_212.npz --spkr 13 --checkpoint models/vctk/bestmodel.pth

completed p318_212.gen_13.wav.
completed p318_212.orig.wav.

> `

**Comment by hepower** [comment]
I met the same problem , before execute download_tools.sh , need to install csh tool with:
sudo apt-get install csh

**Comment by adampolyak** [comment]
_tools_ directory should be in the same directory as generate.py.

**Comment by vivekruhela** [comment]
I am getting the same problem in generate.ipynb. I tried reinstalling SPTK and sch also but still not solved. Error message is as follows:
`CalledProcessError: Command 'echo 1 1 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4  | /home/akanksha/deep_learning/loop/tools/SPTK-3.9/x2x +af > /tmp/gen/weight' returned non-zero exit status 127`
