### ISSUE TITLE
Training data is slow.

### ISSUE THREAD

**Issue by jaxlinksync** [facebookresearch/loop#19]
I'm on the section where training the data. It took 10hrs for the first 33 epochs out of 90. Is it normal or did I miss something? I'm new to this so I'm not that expert in this field.

Thanks.

**Comment by hepower** [comment]
Hi,

I am training the data download on a Ubuntu machine with GPU, it finished 12 epoch with 4 hours, average 20 minutes per epoch for training and evaluation, so I think your performance is same as me.

**Comment by jaxlinksync** [comment]
Thanks.
