### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by jdbermeol** [facebookresearch/loop#2]
Hi, and thank you for realizing your code. Currently, I'm trying to reproduce VCTK results on an ec2 instance with a Kepler GPU, and more than an issue I have a question:

Tqdm report shows iterations are taking around 9 seconds:

`Train (loss 50.62) epoch 2:  28%|##7       | 35/126 [05:01<13:02,  8.60s/it]`
`Train (loss 48.54) epoch 2:  40%|####      | 51/126 [07:29<12:21,  9.89s/it]`

And nvidia-smi shows a very low memory usage:

`1208MiB / 11439MiB`

So, I'm not sure if I'm missing something or if that is the expected performance.

Thanks.

**Comment by adampolyak** [comment]
This is indeed the expected performance, low memory consumption is due to short sequence length(100). In our experiments, we observed that increasing the sequence length didn't improve the performance.
