### ISSUE TITLE
Adding new datasets to train

### ISSUE THREAD

**Issue by jaxlinksync** [facebookresearch/loop#21]
Hi, 

How can you add new datasets (voices) for training? I want to use this datasets. https://linksync-2032.kxcdn.com/wp-content/uploads/2017/06/female-voice-1.zip

they are all in .wav files and I want them to add as a dataset so I can use that voice.

**Comment by ankitmishra262** [comment]
I'm stuck on the same step, referring to my [previous comment](https://github.com/facebookresearch/loop/issues/11#issuecomment-333752158)

**Comment by jaxlinksync** [comment]
I'm having a problem in running this https://gist.github.com/kastnerkyle/001a58a58d090658ee5350cb6129f857
to run extract_feats.py. Any ideas where I can download the kk_all_deps.tar.gz?

**Comment by jaxlinksync** [comment]
I created my own kk_all_deps.tar.gz but now encountered a new error.
```
Makefile:102: recipe for target 'ch_lab' failed
config/rules/targets.mak:55: recipe for target 'main' failed
Traceback (most recent call last):
  File "install_tts.py", line 183, in <module>
    pe(make_cmd)
  File "install_tts.py", line 114, in pe
    for line in execute(cmd, shell=shell):
  File "install_tts.py", line 107, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4']' returned non-zero exit status 2
```

**Comment by adampolyak** [comment]
Closing. Duplicate issue #11 .
