### ISSUE TITLE
RuntimeError: invalid argument 6: expected 3D tensor at /home/a524yangsen/soft/pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:442

### ISSUE THREAD

**Issue by yangsenit** [facebookresearch/loop#24]
when i run the command provided by the document
python train.py --expName vctk --data data/vctk --noise 4 --seq-len 100 --epochs 90

i counter the problem ,what is wrong? would you help me?
RuntimeError: invalid argument 6: expected 3D tensor at /home/a524yangsen/soft/pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:442

**Comment by adampolyak** [comment]
Please make sure that you are using PyTorch 0.1.12, later version have API changes.

**Comment by sausax** [comment]
Add alpha_t.unsqueeze_(1) before https://github.com/facebookresearch/loop/blob/master/model.py#L119
