### ISSUE TITLE
Can we use multi-GPU to make the training faster? How?

### ISSUE THREAD

**Issue by jaxlinksync** [facebookresearch/loop#30]

**Comment by enk100** [comment]
Currently the code is not prepare for multigpu training. 
It is possible to training with multigpu, one way is to use nn.dataparallel, but you also need to modify the state of the model, as you can't save parameters during the forward process. 
Good luck!

**Comment by hepower** [comment]
@enk100 ,
How to modify the code to support multiple-gpu?
Could you please explain more details?
