### ISSUE TITLE
Error when synthesis wave with the download model. 

### ISSUE THREAD

**Issue by hepower** [facebookresearch/loop#31]
Hi,

When I try to generate some waves using the download model, it has some errors when dealing with some sentences, the error type is same, not sure why. Could you please help?

**Sentence1:**
The boy's grandmother is his legal guardian.
**Cmd:**
python generate.py  --text "The boy's grandmother is his legal guardian." --spkr 1 --checkpoint models/vctk/bestmodel.pth
**Error:**
Traceback (most recent call last):
  File "generate.py", line 151, in <module>
    main()
  File "generate.py", line 140, in main
    norm_path)
  File "/kaldi/loop/utils.py", line 266, in generate_merlin_wav
    base_r0=files['mgc'] + '_r0'), shell=True)
  File "/kaldi/loop/utils.py", line 121, in pe
    for line in execute(cmd, shell=shell):
  File "/kaldi/loop/utils.py", line 114, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '/kaldi/loop/tools/bin/SPTK-3.9/freqt -m 59 -a 0.58 -M 511 -A 0 < The_boy's_grandmother_is_his_legal_guardian..gen_1.mgc | /kaldi/loop/tools/bin/SPTK-3.9/c2acr -m 511 -M 0 -l 1024 > The_boy's_grandmother_is_his_legal_guardian..gen_1.mgc_r0' returned non-zero exit status 2

**Sentence2:**
When he's able to return to campaigning, Santorum will have to decide whether he wants to.
**Cmd:**
python generate.py  --text "When he's able to return to campaigning, Santorum will have to decide whether he wants to." --spkr 1 --checkpoint models/vctk/bestmodel.pth
**Error:**
Traceback (most recent call last):
  File "generate.py", line 151, in <module>
    main()
  File "generate.py", line 140, in main
    norm_path)
  File "/kaldi/loop/utils.py", line 266, in generate_merlin_wav
    base_r0=files['mgc'] + '_r0'), shell=True)
  File "/kaldi/loop/utils.py", line 121, in pe
    for line in execute(cmd, shell=shell):
  File "/kaldi/loop/utils.py", line 114, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command '/kaldi/loop/tools/bin/SPTK-3.9/freqt -m 59 -a 0.58 -M 511 -A 0 < When_he's_able_to_return_to_campaigning,_Santorum_will_have_to_decide_whether_he_wants_to..gen_1.mgc | /kaldi/loop/tools/bin/SPTK-3.9/c2acr -m 511 -M 0 -l 1024 > When_he's_able_to_return_to_campaigning,_Santorum_will_have_to_decide_whether_he_wants_to..gen_1.mgc_r0' returned non-zero exit status 2

**Comment by enk100** [comment]
It was problem with the filename, due to ' . should be fixed now.
