### ISSUE TITLE
How to train the samples obtained from public？too much noise and speed too fast!

### ISSUE THREAD

**Issue by lvenoxi** [facebookresearch/loop#37]
I obtain some samples from public, but these samples are too much noise and speed too fast. After training, I found that generated sound  is very vague，can not separate tone and tone. How to train these noisy and faster sound samples？thanks!

**Comment by adampolyak** [comment]
Samples found in the wild are generally hard to train with. The feature extraction script performs phoneme alignment - which will help the training process by marking silence and pause sections.
