### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by jaxlinksync** [facebookresearch/loop#39]
Hi,

So I have run the training a 4 months ago and there was no issue. But now when I add new a dataset and train with multiple speakers I get this error.

`cuda runtime error (59) : device-side assert triggered at /b/wheel/pytorch-src/torch/lib/THC/generic/THCTensorMath.cu:226`

Can you please help?

**Comment by jaxlinksync** [comment]
![image](https://user-images.githubusercontent.com/28586986/35497855-eaf9a116-0506-11e8-82d2-4a9ec2a54748.png)

**Comment by adampolyak** [comment]
Did you train on a new dataset? The error happens because you use try to embed an index which is larger than the size of the loopup table (either for speakers or phonemes).

You might want to increase the number of speakers/phonemes in the training script and see how it goes.
