### ISSUE TITLE
What does a good loss curve look like?

### ISSUE THREAD

**Issue by PetrochukM** [facebookresearch/loop#51]
After the first 90 epochs, I attained a loss of 36. Starting on the next 90 epochs with reduced noise and increased sequence length, it's dropped to 26.

How low should it get to for a quality model?

**Comment by ghostcow** [comment]
The lowest I got with any data was about 25.
What data are you training on?

**Comment by adampolyak** [comment]
The loss depends on how noisy your dataset is and the amount of noise you train with. 
25-26 is about right for vctk training.
