### ISSUE TITLE
How long speech I can synthesize from the text?

### ISSUE THREAD

**Issue by jinserk** [facebookresearch/loop#6]
I've tried, and it works well. Thanks for sharing the great project!
I wonder how long speech it can generate from text. It seems limited < 3 secs if I tried a little long sentence. Where the limit is originated from and how to make it longer? Is it related to the ```--seq-len``` option in training?
Thank you!

**Comment by ytaigman** [comment]
It's currently set to train on ~3sec samples or truncate (max-seq-len argument), so I'd keep sentence length around that.

**Comment by hepower** [comment]
@ytaigman , currently we have max-seq-len = 1000 during training,  I have check the relationship of audio_feature length with the length of corresponding wave file.
343 -> 1724ms 
697 -> 3569ms
seems 5ms for 1 seq.
so should I understand current we support 5 seconds length of wave synthesize ?
