### ISSUE TITLE
self.training？

### ISSUE THREAD

**Issue by DabiaoMa** [facebookresearch/loop#9]
Hi, I am reading your code and the code is really clean. 
I noticed that in the class 'Loop' and 'Decoder' in python file 'model.py', 'self.training' is not defined but used as a condition statement. The inherited class 'torch.nn.Module' doesn't have an attribute named 'training' either.

**Comment by adampolyak** [comment]
Training flag is defined in nn.Module:
https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L58

**Comment by DabiaoMa** [comment]
Thanks, I asked a naive question
